// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  this.Stopwatch = (function() {
    var dir, draw, el, interval, previous_time, self, start_time, stop_time, time, update;

    Stopwatch.UP = 0;

    Stopwatch.DOWN = 1;

    previous_time = null;

    interval = null;

    self = null;

    time = null;

    start_time = null;

    stop_time = null;

    el = null;

    dir = null;

    function Stopwatch(element, direction, minutes, seconds) {
      if (element == null) {
        element = null;
      }
      if (minutes == null) {
        minutes = 0;
      }
      if (seconds == null) {
        seconds = 0;
      }
      el = element;
      start_time = new Date(0);
      start_time.setMinutes(minutes);
      start_time.setSeconds(seconds);
      dir = direction;
      self = this;
    }

    Stopwatch.prototype.reset = function() {
      time = start_time;
      if (el !== null) {
        return draw();
      }
    };

    Stopwatch.prototype.start = function(stopTime) {
      if (stop_time == null) {
        stop_time = stopTime;
      }
      previous_time = new Date();
      return interval = setInterval(update, 100);
    };

    Stopwatch.prototype.stop = function() {
      return clearInterval(interval);
    };

    update = function() {
      var current_time, diff, milli;
      current_time = new Date();
      diff = current_time.getTime() - previous_time.getTime();
      if (dir === Stopwatch.DOWN) {
        milli = time.getTime() - diff;
        if ((stop_time != null) && milli <= stop_time.getMilliseconds()) {
          self.stop();
        } else {
          time.setTime(milli);
        }
      } else {
        milli = time.getTime() + diff;
        if ((stop_time != null) && milli >= stop_time.getMilliseconds()) {
          self.stop();
        } else {
          time.setTime(milli);
        }
      }
      if (el !== null) {
        draw();
      }
      return previous_time = current_time;
    };

    draw = function() {
      var min, sec;
      min = time.getMinutes();
      if (min < 10) {
        min = "0" + min;
      }
      sec = time.getSeconds();
      if (sec < 10) {
        sec = "0" + sec;
      }
      return el.innerHTML = min + ':' + sec;
    };

    return Stopwatch;

  })();

}).call(this);
